packages:
  - 'packages/*'

catalogs:
  fs-extra:
    fs-extra: ^11.3.2
    '@types/fs-extra': ^11.0.4

strictDepBuilds: true

onlyBuiltDependencies:
  - esbuild
  - '@tailwindcss/oxide'

allowBuilds:
  esbuild: false
