import type { PrunedMetadata, TrackMetadataLookup } from '@fauxfetus/data-generator';
import fs from 'fs-extra';
import { join } from 'path';

let lookupMemo: TrackMetadataLookup | null = null;
let lookupPromise: Promise<TrackMetadataLookup> | null = null;

/**
 * Load the per-track metadata sidecar from
 * `static/data/track-metadata.json`. The file is generated by
 * `DataGenerator.writeTrackMetadataJson` and contains exactly the
 * fields the site's `MetadataTable` component renders, keyed by
 * `audioUrl`. It is roughly 1.4 MB — the bulk of the original
 * `metadata` payload (cover art, unused tag categories) is stripped
 * at generation time so this lookup stays cheap.
 *
 * Memoized for the lifetime of the process — the file is read at
 * most once, even though the track page's server load function calls
 * this for every prerendered track.
 */
const loadLookup = async (): Promise<TrackMetadataLookup> => {
	if (lookupMemo) return lookupMemo;
	if (lookupPromise) return lookupPromise;

	const path = join(process.cwd(), 'static', 'data', 'track-metadata.json');

	lookupPromise = fs
		.readJson(path)
		.then((data: TrackMetadataLookup) => {
			lookupMemo = data;
			return data;
		})
		.catch((err) => {
			// Allow retry on next call if the read failed (e.g. first call
			// raced with generate:data in dev).
			lookupPromise = null;
			throw err;
		});

	return lookupPromise;
};

/**
 * Look up the pruned metadata for a single track by its `audioUrl`.
 * Returns `undefined` if the track has no entry in the sidecar
 * (which can happen for stale slugs after a rename, or before
 * `pnpm generate:data` has been run).
 */
export const readTrackMetadata = async (audioUrl: string): Promise<PrunedMetadata | undefined> => {
	const lookup = await loadLookup();
	return lookup[audioUrl];
};
